version: "3.3"
services:
  web:
    container_name: app
    build: ./web
    command: node app.js
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - backend

  api:
    container_name: api
    build: ./api
    command: npm start
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
